name: Publish production docker image
on:
  push:
    tags:
      - "v*"
jobs:
  build:
    runs-on: [linux]
    name: Build and push production image
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          SSH_KEY: ${{ secrets.GH_SSH_KEY }}
        with:
          name: bitfocus/companion-worker-modules
          registry: docker.oal.no
          username: ${{ secrets.OALDOCKER_USERNAME }}
          password: ${{ secrets.OALDOCKER_PASSWORD }}
          workdir: ./
          tag_semver: true
          buildargs: SSH_KEY
